<?php

namespace Proxies\__CG__\EcoJob\CandidatBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CuVi extends \EcoJob\CandidatBundle\Entity\CuVi implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'id', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'nom', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'prenom', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'telephone', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'about', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'imageFile', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'imageName', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'updatedAt', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'poste', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'latitude', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'longitude', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'localisation', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'experience', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'secteur', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'showable'];
        }

        return ['__isInitialized__', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'id', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'nom', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'prenom', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'telephone', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'about', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'imageFile', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'imageName', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'updatedAt', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'poste', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'latitude', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'longitude', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'localisation', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'experience', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'secteur', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CuVi' . "\0" . 'showable'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CuVi $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbout($about)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbout', [$about]);

        return parent::setAbout($about);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbout', []);

        return parent::getAbout();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageName($imageName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageName', [$imageName]);

        return parent::setImageName($imageName);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageName', []);

        return parent::getImageName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFile(\Symfony\Component\HttpFoundation\File\File $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFile', [$image]);

        return parent::setImageFile($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFile', []);

        return parent::getImageFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoste($poste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoste', [$poste]);

        return parent::setPoste($poste);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoste', []);

        return parent::getPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalisation($localisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalisation', [$localisation]);

        return parent::setLocalisation($localisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalisation', []);

        return parent::getLocalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setExperience($experience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperience', [$experience]);

        return parent::setExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperience', []);

        return parent::getExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function addSecteur(\EcoJob\RecruteurBundle\Entity\ContratCategorie $secteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSecteur', [$secteur]);

        return parent::addSecteur($secteur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSecteur(\EcoJob\RecruteurBundle\Entity\ContratCategorie $secteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSecteur', [$secteur]);

        return parent::removeSecteur($secteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecteur', []);

        return parent::getSecteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setShowable($showable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShowable', [$showable]);

        return parent::setShowable($showable);
    }

    /**
     * {@inheritDoc}
     */
    public function getShowable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShowable', []);

        return parent::getShowable();
    }

}
