<?php

namespace Proxies\__CG__\EcoJob\CandidatBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CVFile extends \EcoJob\CandidatBundle\Entity\CVFile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'id', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'cvFile', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'cvName', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'updatedAt', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'lm'];
        }

        return ['__isInitialized__', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'id', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'cvFile', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'cvName', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'updatedAt', '' . "\0" . 'EcoJob\\CandidatBundle\\Entity\\CVFile' . "\0" . 'lm'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CVFile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvName($cvName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvName', [$cvName]);

        return parent::setCvName($cvName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvName', []);

        return parent::getCvName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCvFile(\Symfony\Component\HttpFoundation\File\File $cv = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCvFile', [$cv]);

        return parent::setCvFile($cv);
    }

    /**
     * {@inheritDoc}
     */
    public function getCvFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCvFile', []);

        return parent::getCvFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setLm($lm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLm', [$lm]);

        return parent::setLm($lm);
    }

    /**
     * {@inheritDoc}
     */
    public function getLm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLm', []);

        return parent::getLm();
    }

}
