<?php

namespace Proxies\__CG__\EcoJob\RecruteurBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Offre extends \EcoJob\RecruteurBundle\Entity\Offre implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'id', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'experience', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'titre', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'contenu', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'contrat', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'recruteur', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'valid', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'suspendu', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'added', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'expired', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'latitude', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'longitude', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'localisation', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'candidatures', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'createdAt', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'expireAt', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'categorie', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'validAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'id', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'experience', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'titre', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'contenu', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'contrat', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'recruteur', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'valid', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'suspendu', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'added', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'expired', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'latitude', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'longitude', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'localisation', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'candidatures', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'createdAt', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'expireAt', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'categorie', '' . "\0" . 'EcoJob\\RecruteurBundle\\Entity\\Offre' . "\0" . 'validAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Offre $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu($contenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', [$contenu]);

        return parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', []);

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setContrat(\EcoJob\RecruteurBundle\Entity\ContratType $contrat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContrat', [$contrat]);

        return parent::setContrat($contrat);
    }

    /**
     * {@inheritDoc}
     */
    public function getContrat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContrat', []);

        return parent::getContrat();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecruteur(\EcoJob\UserBundle\Entity\User $recruteur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecruteur', [$recruteur]);

        return parent::setRecruteur($recruteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecruteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecruteur', []);

        return parent::getRecruteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setExperience($experience)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperience', [$experience]);

        return parent::setExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperience()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperience', []);

        return parent::getExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setValid($valid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValid', [$valid]);

        return parent::setValid($valid);
    }

    /**
     * {@inheritDoc}
     */
    public function getValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValid', []);

        return parent::getValid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdded($added)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdded', [$added]);

        return parent::setAdded($added);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdded()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdded', []);

        return parent::getAdded();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalisation($localisation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalisation', [$localisation]);

        return parent::setLocalisation($localisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalisation', []);

        return parent::getLocalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function addCandidature(\EcoJob\CandidatBundle\Entity\Candidature $candidature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCandidature', [$candidature]);

        return parent::addCandidature($candidature);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuspendu($suspendu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuspendu', [$suspendu]);

        return parent::setSuspendu($suspendu);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuspendu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuspendu', []);

        return parent::getSuspendu();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpireAt($expireAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpireAt', [$expireAt]);

        return parent::setExpireAt($expireAt);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCandidature(\EcoJob\CandidatBundle\Entity\Candidature $candidature)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCandidature', [$candidature]);

        return parent::removeCandidature($candidature);
    }

    /**
     * {@inheritDoc}
     */
    public function getCandidatures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCandidatures', []);

        return parent::getCandidatures();
    }

    /**
     * {@inheritDoc}
     */
    public function getExpireAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpireAt', []);

        return parent::getExpireAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\EcoJob\RecruteurBundle\Entity\ContratCategorie $categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($expired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', [$expired]);

        return parent::setExpired($expired);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpired', []);

        return parent::getExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidAt($validAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidAt', [$validAt]);

        return parent::setValidAt($validAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidAt', []);

        return parent::getValidAt();
    }

}
